#!/bin/bash

export NEXUS_VERSION=2.11.2-06

export NEXUS_APP_DIR=nexus-${NEXUS_VERSION}
export NEXUS_BUNDLE_FILE=nexus-${NEXUS_VERSION}-bundle.tar.gz
export NEXUS_BUNDLE_URL=http://www.sonatype.org/downloads/$NEXUS_BUNDLE_FILE

# Remove for testing.
# rm -rf `find $OPENSHIFT_DATA_DIR -name nexus-*`

#
# Download the Sonatype Nexus bundle if it doesn't exist.
#
if [ -d "$OPENSHIFT_DATA_DIR/$NEXUS_APP_DIR" ]; then
        echo "Sonatype Nexus $NEXUS_VERSION already exists in $OPENSHIFT_DATA_DIR"
else
        echo "Removing old Sonatype Nexus distributions"
        rm -rf `find $OPENSHIFT_DATA_DIR -name nexus-*`

        # download the new distribution
        if [ -d "$OPENSHIFT_TMP_DIR/$NEXUS_BUNDLE_FILE" ]; then
                echo "Sonatype Nexus $NEXUS_VERSION exists in $OPENSHIFT_TMP_DIR"
        else
                echo "Downloading Sonatype Nexus $NEXUS_VERSION to $OPENSHIFT_TMP_DIR/$NEXUS_BUNDLE_FILE"
                wget $NEXUS_BUNDLE_URL -O $OPENSHIFT_TMP_DIR/$NEXUS_BUNDLE_FILE
	fi

        echo "Extracting Sonatype Nexus $NEXUS_VERSION to $NEXUS_BUNDLE_FILE"
        tar -xzf $OPENSHIFT_TMP_DIR/$NEXUS_BUNDLE_FILE -C $OPENSHIFT_TMP_DIR

        echo "Copying Sonatype Nexus $NEXUS_VERSION to $OPENSHIFT_DATA_DIR"
        mv $OPENSHIFT_TMP_DIR/$NEXUS_APP_DIR $OPENSHIFT_DATA_DIR/

        # only copy sonatype-work if folder doesn't exist
        if [ -d "$OPENSHIFT_DATA_DIR/sonatype-work" ]; then
                echo "Sonatype Nexus $NEXUS_VERSION workspace already exists"
                rm -rf $OPENSHIFT_TMP_DIR/sonatype-work
        else
                echo "Creating Sonatype Nexus $NEXUS_VERSION workspace"
                mv $OPENSHIFT_TMP_DIR/sonatype-work $OPENSHIFT_DATA_DIR/
        fi
fi

# Overwrite default configurations
echo "Overwrite Sonatype Nexus $NEXUS_VERSION configs with repo configurations"
cp -R $OPENSHIFT_REPO_DIR/conf $OPENSHIFT_DATA_DIR/$NEXUS_APP_DIR/

echo "Removing Sonatype log directory, replacing with link to OPENSHIFT logs directory"
cd $OPENSHIFT_DATA_DIR/$NEXUS_APP_DIR
rm -rf logs
ln -s $OPENSHIFT_DIY_LOG_DIR logs

echo "ensuring pseudo userhome exists"
mkdir -p $OPENSHIFT_DATA_DIR/userhome

echo "updating wrapper"
rm ${OPENSHIFT_DATA_DIR}/$NEXUS_APP_DIR/bin/jsw/lib/libwrapper-*
rm ${OPENSHIFT_DATA_DIR}/$NEXUS_APP_DIR/bin/jsw/lib/wrapper-*
rm ${OPENSHIFT_DATA_DIR}/$NEXUS_APP_DIR/bin/jsw/linux-x86-64/wrapper
curl -o ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9.tar.gz http://wrapper.tanukisoftware.com/download/3.5.9/wrapper-delta-pack-3.5.9.tar.gz
tar -zxvf ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9.tar.gz -C ${OPENSHIFT_DATA_DIR}
rm ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9.tar.gz
cp ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9/lib/wrapper.jar ${OPENSHIFT_DATA_DIR}/$NEXUS_APP_DIR/bin/jsw/lib/wrapper-3.2.3.jar
cp ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9/bin/wrapper-linux-x86-64 ${OPENSHIFT_DATA_DIR}/$NEXUS_APP_DIR/bin/jsw/linux-x86-64/wrapper
cp ${OPENSHIFT_DATA_DIR}wrapper-delta-pack-3.5.9/lib/libwrapper-linux-x86-64.so ${OPENSHIFT_DATA_DIR}/$NEXUS_APP_DIR/bin/jsw/lib/libwrapper.so

echo "wrapper.backend.type=PIPE" >> ${OPENSHIFT_DATA_DIR}/$NEXUS_APP_DIR/bin/jsw/conf/wrapper.conf
