#!/bin/bash

export NEXUS_VERSION=2.8.1-01

export NEXUS_APP_DIR=nexus-${NEXUS_VERSION}
export NEXUS_BUNDLE_FILE=nexus-${NEXUS_VERSION}-bundle.tar.gz
export NEXUS_BUNDLE_URL=http://www.sonatype.org/downloads/$NEXUS_BUNDLE_FILE

# Remove for testing.
# rm -rf `find $OPENSHIFT_DATA_DIR -name nexus-*`

#
# Download the Sonatype Nexus bundle if it doesn't exist.
#
if [ -d "$OPENSHIFT_DATA_DIR/$NEXUS_APP_DIR" ]; then
        echo "Sonatype Nexus $NEXUS_VERSION already exists in $OPENSHIFT_DATA_DIR"
else 
        echo "Removing old Sonatype Nexus distributions"
        rm -rf `find $OPENSHIFT_DATA_DIR -name nexus-*`

        # download the new distribution
        if [ -d "$OPENSHIFT_TMP_DIR/$NEXUS_BUNDLE_FILE" ]; then
                echo "Sonatype Nexus $NEXUS_VERSION exists in $OPENSHIFT_TMP_DIR"
        else 
                echo "Downloading Sonatype Nexus $NEXUS_VERSION to $OPENSHIFT_TMP_DIR/$NEXUS_BUNDLE_FILE"
                wget $NEXUS_BUNDLE_URL -O $OPENSHIFT_TMP_DIR/$NEXUS_BUNDLE_FILE                
	fi

        echo "Extracting Sonatype Nexus $NEXUS_VERSION to $NEXUS_BUNDLE_FILE"
        tar -xzf $OPENSHIFT_TMP_DIR/$NEXUS_BUNDLE_FILE -C $OPENSHIFT_TMP_DIR

        echo "Copying Sonatype Nexus $NEXUS_VERSION to $OPENSHIFT_DATA_DIR"
        mv $OPENSHIFT_TMP_DIR/$NEXUS_APP_DIR $OPENSHIFT_DATA_DIR/

        # only copy sonatype-work if folder doesn't exist
        if [ -d "$OPENSHIFT_DATA_DIR/sonatype-work" ]; then
                echo "Sonatype Nexus $NEXUS_VERSION workspace already exists"
                rm -rf $OPENSHIFT_TMP_DIR/sonatype-work
        else
                echo "Creating Sonatype Nexus $NEXUS_VERSION workspace"
                mv -R $OPENSHIFT_TMP_DIR/sonatype-work $OPENSHIFT_DATA_DIR/
        fi
fi

# Overwrite default configurations
echo "Overwrite Sonatype Nexus $NEXUS_VERSION configs with repo configurations"
cp -R $OPENSHIFT_REPO_DIR/conf $OPENSHIFT_DATA_DIR/$NEXUS_APP_DIR/
