#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

# script defined variables
export NEXUS_NAME=`ls $OPENSHIFT_DATA_DIR | grep nexus-*`

#
# Environment variables
#
# https://support.sonatype.com/entries/30145206-Q-Can-I-override-Nexus-configuration-properties-with-environment-variables-
export NEXUS_APPLICATION_PORT=$OPENSHIFT_DIY_PORT
export NEXUS_APPLICATION_HOST=$OPENSHIFT_DIY_IP
export NEXUS_CONTEXT_PATH=/
export NEXUS_WORK=$OPENSHIFT_DATA_DIR/sonatype-work
export NEXUS_HOME=$OPENSHIFT_DATA_DIR/$NEXUS_NAME

# Launch the Jetty server directly.
java -cp $NEXUS_HOME/lib/*:$NEXUS_HOME/conf/ \
-Djava.net.preferIPv4Stack=true \
-Dcom.sun.jndi.ldap.connect.pool.protocol="plain ssl" \
org.sonatype.nexus.bootstrap.Launcher \
$NEXUS_HOME/conf/jetty.xml \
$NEXUS_HOME/conf/jetty-requestlog.xml \
> $OPENSHIFT_DIY_LOG_DIR/out.log &

echo "Sonatype Nexus will be started"