#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

# script defined variables
export NEXUS_NAME=`ls $OPENSHIFT_DATA_DIR | grep nexus-*`

#
# Environment variables
#
# https://support.sonatype.com/entries/30145206-Q-Can-I-override-Nexus-configuration-properties-with-environment-variables-
export NEXUS_APPLICATION_PORT=$OPENSHIFT_DIY_PORT
export NEXUS_APPLICATION_HOST=$OPENSHIFT_DIY_IP
export NEXUS_CONTEXT_PATH=/
export NEXUS_WORK=$OPENSHIFT_DATA_DIR/sonatype-work
export NEXUS_HOME=$OPENSHIFT_DATA_DIR/$NEXUS_NAME
export _JAVA_OPTIONS=-Duser.home=$OPENSHIFT_DATA_DIR/userhome

# Launch the nexus app using the provided start script.
cd $NEXUS_HOME
bin/nexus start

echo "Sonatype Nexus will be started"
