#!/bin/bash

# The logic to stop your application should be put in this script.
if [ -z "$(ps -ef | grep java | grep -v grep)" ]
then
    echo "Application is not running"
else
	echo "Application will be stopped"
    kill `ps -ef | grep java | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi
